language: go
go:
  - 1.11

before_script:
  - go get github.com/go-check/check
  - wget https://s3.amazonaws.com/stockfish/stockfish-7-linux.zip
  - unzip stockfish-7-linux.zip
  - cp "stockfish-7-linux/Linux/stockfish 7 x64" stockfish
  - chmod +x stockfish

before_install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  - goveralls -repotoken iDcWiqj8EELzhlCi1xr0wazaGYHLFHp1a
